from flask import Flask, request, jsonify, make_response
#from datetime import datetime
from model_builder.modelBuild import ModelBuilderHandle
from model_store.controller.challenge_schema import ChallengeInput
from marshmallow import ValidationError
from model_store.persistency.persistency import Challenge_esi
from model_store.controller.challenge_schema import ChallengeInput, GetChallenge

import os

app = Flask(__name__)

mbh = ModelBuilderHandle()
CSVfile = "C:\\Users\\user1\\SearchEngine\\repository\\data\\ChallengeData.csv"

c_esi = Challenge_esi()


@app.route('/')
def index():
    return 'Hello World'

@app.route('/buildmodel', methods = ["GET"])    
def buildmodel():
    text = mbh.textProcessor(csv_file = CSVfile)
    print('got text')

    _count_vect, _tfidf_transformer, _train_tfidf = mbh.build_model(text = text)
    
    return ('processed successfully')
     
@app.route('/insertes', methods = ["POST"])    
def insert_es(): 
    #posted data in json format
    request_json = request.json
    try:
        #deserializing json request data
        data = ChallengeInput().load(request_json)
        #extracting challenge_id, challenge_title and text from posted data
        #challenge_id, challenge_title, text = data['challenge_id'], data['challenge_title'], data['text']
    except ValidationError as err: #in the case of incompatible parameters in data posted
        return jsonify(err.messages), 400   #response object and status code

    #insert into elastic search 
    #try:
    print(data)
    response = c_esi.insert_update_challenge(data)
    print(type(response))
    return jsonify(response), 200 #response object and status code

    # except Exception as err:
    #     print(err)
    #     return "Insert/Update unsuccessful"


@app.route('/getChallenge')
def get_challenge():
    request_data = request.args
    schema = GetChallenge()
    try:
        data = schema.load(request_data)
        challenge_id = data['challenge_id']
        print(challenge_id)

    except ValidationError as err:
        print("validation error")
        return jsonify(err.messages), 400

    try:
        response_data = c_esi.get_challenge(challenge_id=challenge_id)
        return jsonify(response_data), 200
    except Exception as err:
        return jsonify({'error: ': err}), 500

@app.route('/getAllChallenges', methods=["GET"])
def get_all_challenges():
    try:
        response_data = c_esi.get_all_challenges()
        return (response_data), 200
    except Exception as err:
        return jsonify({'error: ': err}), 500

if __name__ == "__main__":
    app.run(debug=True)    
    